### --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#                                      Customer Churn Using ANN

### --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [2]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
%matplotlib inline

In [3]:
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [4]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [5]:
df.TotalCharges = pd.to_numeric(df.TotalCharges,errors='coerce')

In [6]:
df.drop('customerID',axis='columns',inplace=True)

In [7]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [8]:
# Checking the Non-numerical/ categorical values
for column in df:
    if(df[column].dtypes=='object'):
        print(f'{column}: {df[column].unique()}')

gender: ['Female' 'Male']
Partner: ['Yes' 'No']
Dependents: ['No' 'Yes']
PhoneService: ['No' 'Yes']
MultipleLines: ['No phone service' 'No' 'Yes']
InternetService: ['DSL' 'Fiber optic' 'No']
OnlineSecurity: ['No' 'Yes' 'No internet service']
OnlineBackup: ['Yes' 'No' 'No internet service']
DeviceProtection: ['No' 'Yes' 'No internet service']
TechSupport: ['No' 'Yes' 'No internet service']
StreamingTV: ['No' 'Yes' 'No internet service']
StreamingMovies: ['No' 'Yes' 'No internet service']
Contract: ['Month-to-month' 'One year' 'Two year']
PaperlessBilling: ['Yes' 'No']
PaymentMethod: ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
Churn: ['No' 'Yes']

In [9]:
# MultipleLines, OnlineSecurity, OnlineBackup and many columns has no internet services whihc means that customers are not able to opearte that facility, so we can consider those cases unser the same 'No' label
df.replace('No internet service','No',inplace=True)
df.replace('No phone service','No',inplace=True)

In [10]:
for column in df:
    if(df[column].dtypes=='object'):
        print(f'{column}: {df[column].unique()}')

gender: ['Female' 'Male']
Partner: ['Yes' 'No']
Dependents: ['No' 'Yes']
PhoneService: ['No' 'Yes']
MultipleLines: ['No' 'Yes']
InternetService: ['DSL' 'Fiber optic' 'No']
OnlineSecurity: ['No' 'Yes']
OnlineBackup: ['Yes' 'No']
DeviceProtection: ['No' 'Yes']
TechSupport: ['No' 'Yes']
StreamingTV: ['No' 'Yes']
StreamingMovies: ['No' 'Yes']
Contract: ['Month-to-month' 'One year' 'Two year']
PaperlessBilling: ['Yes' 'No']
PaymentMethod: ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
Churn: ['No' 'Yes']

In [11]:
# now we can encode the yes:1, no:0 very easily and train the ANN

In [12]:
label_encode_columns = []
for column in df:
    if(df[column].dtypes=='object'):
        label_encode_columns.append(column)
        #print(f'{column}: {df[column].unique()}')

In [13]:
label_encode_columns

['gender',
 'Partner',
 'Dependents',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'Churn']

In [14]:
# We won't apply yes no encoding on these
# gender
# InternetService: ['DSL' 'Fiber optic' 'No']
# Contract: ['Month-to-month' 'One year' 'Two year']
# PaymentMethod: ['Electronic check' 'Mailed check' 'Bank transfer (automatic)' 'Credit card (automatic)']

In [15]:
label_encode_columns.remove('gender')
label_encode_columns.remove('InternetService')
label_encode_columns.remove('Contract')
label_encode_columns.remove('PaymentMethod')

In [16]:
label_encode_columns

['Partner',
 'Dependents',
 'PhoneService',
 'MultipleLines',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'PaperlessBilling',
 'Churn']

In [17]:
for i in label_encode_columns:
    df[i].replace({'Yes':1,'No':0},inplace=True)

In [18]:
df['gender'].replace({'Female':0,'Male':1},inplace=True)

In [19]:
for column in df:
    print(f'{column}: {df[column].unique()}')

gender: [0 1]
SeniorCitizen: [0 1]
Partner: [1 0]
Dependents: [0 1]
tenure: [ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26  0
 39]
PhoneService: [0 1]
MultipleLines: [0 1]
InternetService: ['DSL' 'Fiber optic' 'No']
OnlineSecurity: [0 1]
OnlineBackup: [1 0]
DeviceProtection: [0 1]
TechSupport: [0 1]
StreamingTV: [0 1]
StreamingMovies: [0 1]
Contract: ['Month-to-month' 'One year' 'Two year']
PaperlessBilling: [1 0]
PaymentMethod: ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
MonthlyCharges: [29.85 56.95 53.85 ... 63.1  44.2  78.7 ]
TotalCharges: [  29.85 1889.5   108.15 ...  346.45  306.6  6844.5 ]
Churn: [0 1]

In [20]:
# InternetService, Contract, PaymentMethod are the columns to which we will apply one hot encoding

In [21]:
df = pd.get_dummies(data=df,columns=['InternetService', 'Contract', 'PaymentMethod'])

In [22]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'PaperlessBilling', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

In [23]:
# removed 3 and added 10 columns so total 20+7 columns

In [24]:
df.dtypes

gender                                       int64
SeniorCitizen                                int64
Partner                                      int64
Dependents                                   int64
tenure                                       int64
PhoneService                                 int64
MultipleLines                                int64
OnlineSecurity                               int64
OnlineBackup                                 int64
DeviceProtection                             int64
TechSupport                                  int64
StreamingTV                                  int64
StreamingMovies                              int64
PaperlessBilling                             int64
MonthlyCharges                             float64
TotalCharges                               float64
Churn                                        int64
InternetService_DSL                          uint8
InternetService_Fiber optic                  uint8
InternetService_No                           uint8
Contract_Month-to-month                      uint8
Contract_One year                            uint8
Contract_Two year                            uint8
PaymentMethod_Bank transfer (automatic)      uint8
PaymentMethod_Credit card (automatic)        uint8
PaymentMethod_Electronic check               uint8
PaymentMethod_Mailed check                   uint8
dtype: object

In [25]:
df.tenure,df.MonthlyCharges, df.TotalCharges

(0        1
 1       34
 2        2
 3       45
 4        2
         ..
 7038    24
 7039    72
 7040    11
 7041     4
 7042    66
 Name: tenure, Length: 7043, dtype: int64,
 0        29.85
 1        56.95
 2        53.85
 3        42.30
 4        70.70
          ...
 7038     84.80
 7039    103.20
 7040     29.60
 7041     74.40
 7042    105.65
 Name: MonthlyCharges, Length: 7043, dtype: float64,
 0         29.85
 1       1889.50
 2        108.15
 3       1840.75
 4        151.65
          ...
 7038    1990.50
 7039    7362.90
 7040     346.45
 7041     306.60
 7042    6844.50
 Name: TotalCharges, Length: 7043, dtype: float64)

In [26]:
# Scaling tenure, monthlycharges, totalcharges between -1 to 1
from sklearn.preprocessing import MinMaxScaler
scl = MinMaxScaler()
df[['tenure','MonthlyCharges','TotalCharges']] = scl.fit_transform(df[['tenure','MonthlyCharges','TotalCharges']])

In [27]:
for column in df:
    print(f'{column}: {df[column].unique()}')

gender: [0 1]
SeniorCitizen: [0 1]
Partner: [1 0]
Dependents: [0 1]
tenure: [0.01388889 0.47222222 0.02777778 0.625      0.11111111 0.30555556
 0.13888889 0.38888889 0.86111111 0.18055556 0.22222222 0.80555556
 0.68055556 0.34722222 0.95833333 0.72222222 0.98611111 0.29166667
 0.16666667 0.41666667 0.65277778 1.         0.23611111 0.375
 0.06944444 0.63888889 0.15277778 0.97222222 0.875      0.59722222
 0.20833333 0.83333333 0.25       0.91666667 0.125      0.04166667
 0.43055556 0.69444444 0.88888889 0.77777778 0.09722222 0.58333333
 0.48611111 0.66666667 0.40277778 0.90277778 0.52777778 0.94444444
 0.44444444 0.76388889 0.51388889 0.5        0.56944444 0.08333333
 0.05555556 0.45833333 0.93055556 0.31944444 0.79166667 0.84722222
 0.19444444 0.27777778 0.73611111 0.55555556 0.81944444 0.33333333
 0.61111111 0.26388889 0.75       0.70833333 0.36111111 0.
 0.54166667]
PhoneService: [0 1]
MultipleLines: [0 1]
OnlineSecurity: [0 1]
OnlineBackup: [1 0]
DeviceProtection: [0 1]
TechSupport: [0 1]
StreamingTV: [0 1]
StreamingMovies: [0 1]
PaperlessBilling: [1 0]
MonthlyCharges: [0.11542289 0.38507463 0.35422886 ... 0.44626866 0.25820896 0.60149254]
TotalCharges: [0.0012751  0.21586661 0.01031041 ... 0.03780868 0.03321025 0.78764136]
Churn: [0 1]
InternetService_DSL: [1 0]
InternetService_Fiber optic: [0 1]
InternetService_No: [0 1]
Contract_Month-to-month: [1 0]
Contract_One year: [0 1]
Contract_Two year: [0 1]
PaymentMethod_Bank transfer (automatic): [0 1]
PaymentMethod_Credit card (automatic): [0 1]
PaymentMethod_Electronic check: [1 0]
PaymentMethod_Mailed check: [0 1]

In [49]:
df.to_csv('Customer-Churn-Encoded.csv')

In [50]:
x = df.drop('Churn',axis=True)
y = df['Churn']

In [29]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=5)

In [30]:
x_train.shape, y_train.shape

((5634, 26), (5634,))

In [31]:
# ANN
import tensorflow as tf
from tensorflow import keras
from keras import Sequential

In [32]:
model = keras.Sequential([
    keras.layers.Dense(units = 20, input_shape=(26,), activation='relu'),
    keras.layers.Dense(units = 15, activation='relu'),
    keras.layers.Dense(units = 1, activation='sigmoid')
])

In [33]:
model.compile(optimizer = 'adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=50)

Epoch 1/50
177/177 [==============================] - 1s 2ms/step - loss: nan - accuracy: 0.7142
Epoch 2/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 3/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 4/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 5/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 6/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 7/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 8/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 9/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 10/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 11/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 12/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 13/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 14/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 15/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 16/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 17/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 18/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 19/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 20/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 21/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 22/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 23/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 24/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 25/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 26/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 27/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 28/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 29/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 30/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 31/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 32/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 33/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 34/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 35/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 36/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 37/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 38/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 39/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 40/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 41/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 42/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 43/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 44/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 45/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 46/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 47/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 48/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 49/50
177/177 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7368
Epoch 50/50
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7368

In [34]:
# we are getting nan loss because we might have encountered some nan values in the input lets see:
df.isnull().sum()

gender                                      0
SeniorCitizen                               0
Partner                                     0
Dependents                                  0
tenure                                      0
PhoneService                                0
MultipleLines                               0
OnlineSecurity                              0
OnlineBackup                                0
DeviceProtection                            0
TechSupport                                 0
StreamingTV                                 0
StreamingMovies                             0
PaperlessBilling                            0
MonthlyCharges                              0
TotalCharges                               11
Churn                                       0
InternetService_DSL                         0
InternetService_Fiber optic                 0
InternetService_No                          0
Contract_Month-to-month                     0
Contract_One year                           0
Contract_Two year                           0
PaymentMethod_Bank transfer (automatic)     0
PaymentMethod_Credit card (automatic)       0
PaymentMethod_Electronic check              0
PaymentMethod_Mailed check                  0
dtype: int64

In [35]:
df.dropna(how='any',inplace=True)

In [36]:
df.isnull().sum()

gender                                     0
SeniorCitizen                              0
Partner                                    0
Dependents                                 0
tenure                                     0
PhoneService                               0
MultipleLines                              0
OnlineSecurity                             0
OnlineBackup                               0
DeviceProtection                           0
TechSupport                                0
StreamingTV                                0
StreamingMovies                            0
PaperlessBilling                           0
MonthlyCharges                             0
TotalCharges                               0
Churn                                      0
InternetService_DSL                        0
InternetService_Fiber optic                0
InternetService_No                         0
Contract_Month-to-month                    0
Contract_One year                          0
Contract_Two year                          0
PaymentMethod_Bank transfer (automatic)    0
PaymentMethod_Credit card (automatic)      0
PaymentMethod_Electronic check             0
PaymentMethod_Mailed check                 0
dtype: int64

In [37]:
# now the null values from the df is removed, 11 rows will be deleted

In [38]:
print(df.shape)
x = df.drop('Churn',axis=True)
y = df['Churn']
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=5)
x_train.shape, x_test.shape

(7032, 27)

((5625, 26), (1407, 26))

In [39]:
# ANN
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
model = keras.Sequential([
    keras.layers.Dense(units = 20, input_shape=(26,), activation='relu'),
    keras.layers.Dense(units = 15, activation='relu'),
    keras.layers.Dense(units = 10, activation='relu'),
    keras.layers.Dense(units = 1, activation='sigmoid')
])
model.compile(optimizer = 'adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=50,validation_split=0.3)

Epoch 1/50

C:\Users\sandeep sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\data_adapter.py:1700: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  return t[start:end]

124/124 [==============================] - 1s 3ms/step - loss: 0.5882 - accuracy: 0.6927 - val_loss: 0.4993 - val_accuracy: 0.7429
Epoch 2/50
124/124 [==============================] - 0s 2ms/step - loss: 0.4441 - accuracy: 0.7854 - val_loss: 0.4439 - val_accuracy: 0.7855
Epoch 3/50
124/124 [==============================] - 0s 2ms/step - loss: 0.4198 - accuracy: 0.8009 - val_loss: 0.4339 - val_accuracy: 0.7891
Epoch 4/50
124/124 [==============================] - 0s 2ms/step - loss: 0.4128 - accuracy: 0.8034 - val_loss: 0.4309 - val_accuracy: 0.7921
Epoch 5/50
124/124 [==============================] - 0s 2ms/step - loss: 0.4117 - accuracy: 0.8021 - val_loss: 0.4282 - val_accuracy: 0.7950
Epoch 6/50
124/124 [==============================] - 0s 2ms/step - loss: 0.4076 - accuracy: 0.8062 - val_loss: 0.4276 - val_accuracy: 0.7927
Epoch 7/50
124/124 [==============================] - 0s 2ms/step - loss: 0.4050 - accuracy: 0.8095 - val_loss: 0.4257 - val_accuracy: 0.7962
Epoch 8/50
124/124 [==============================] - 0s 2ms/step - loss: 0.4052 - accuracy: 0.8077 - val_loss: 0.4382 - val_accuracy: 0.7832
Epoch 9/50
124/124 [==============================] - 0s 2ms/step - loss: 0.4049 - accuracy: 0.8080 - val_loss: 0.4284 - val_accuracy: 0.7980
Epoch 10/50
124/124 [==============================] - 0s 2ms/step - loss: 0.4024 - accuracy: 0.8108 - val_loss: 0.4255 - val_accuracy: 0.7950
Epoch 11/50
124/124 [==============================] - 0s 2ms/step - loss: 0.4015 - accuracy: 0.8077 - val_loss: 0.4247 - val_accuracy: 0.7974
Epoch 12/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3996 - accuracy: 0.8136 - val_loss: 0.4334 - val_accuracy: 0.7838
Epoch 13/50
124/124 [==============================] - 0s 2ms/step - loss: 0.4029 - accuracy: 0.8164 - val_loss: 0.4262 - val_accuracy: 0.7962
Epoch 14/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3986 - accuracy: 0.8123 - val_loss: 0.4242 - val_accuracy: 0.8009
Epoch 15/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3977 - accuracy: 0.8146 - val_loss: 0.4260 - val_accuracy: 0.7986
Epoch 16/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3949 - accuracy: 0.8164 - val_loss: 0.4282 - val_accuracy: 0.7891
Epoch 17/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3975 - accuracy: 0.8156 - val_loss: 0.4242 - val_accuracy: 0.8015
Epoch 18/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3946 - accuracy: 0.8199 - val_loss: 0.4300 - val_accuracy: 0.7927
Epoch 19/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3940 - accuracy: 0.8164 - val_loss: 0.4254 - val_accuracy: 0.7980
Epoch 20/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3928 - accuracy: 0.8186 - val_loss: 0.4257 - val_accuracy: 0.8021
Epoch 21/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3917 - accuracy: 0.8199 - val_loss: 0.4275 - val_accuracy: 0.7956
Epoch 22/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3914 - accuracy: 0.8202 - val_loss: 0.4285 - val_accuracy: 0.7980
Epoch 23/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3924 - accuracy: 0.8189 - val_loss: 0.4276 - val_accuracy: 0.7927
Epoch 24/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3890 - accuracy: 0.8212 - val_loss: 0.4297 - val_accuracy: 0.8009
Epoch 25/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3884 - accuracy: 0.8204 - val_loss: 0.4275 - val_accuracy: 0.7998
Epoch 26/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3868 - accuracy: 0.8235 - val_loss: 0.4262 - val_accuracy: 0.7998
Epoch 27/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3880 - accuracy: 0.8247 - val_loss: 0.4279 - val_accuracy: 0.7962
Epoch 28/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3863 - accuracy: 0.8209 - val_loss: 0.4282 - val_accuracy: 0.7986
Epoch 29/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3851 - accuracy: 0.8237 - val_loss: 0.4291 - val_accuracy: 0.7974
Epoch 30/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3841 - accuracy: 0.8237 - val_loss: 0.4311 - val_accuracy: 0.7950
Epoch 31/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3830 - accuracy: 0.8230 - val_loss: 0.4317 - val_accuracy: 0.7927
Epoch 32/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3843 - accuracy: 0.8245 - val_loss: 0.4355 - val_accuracy: 0.7915
Epoch 33/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3815 - accuracy: 0.8247 - val_loss: 0.4325 - val_accuracy: 0.7879
Epoch 34/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3827 - accuracy: 0.8245 - val_loss: 0.4296 - val_accuracy: 0.8009
Epoch 35/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3801 - accuracy: 0.8212 - val_loss: 0.4339 - val_accuracy: 0.7903
Epoch 36/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3813 - accuracy: 0.8265 - val_loss: 0.4295 - val_accuracy: 0.7956
Epoch 37/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3790 - accuracy: 0.8247 - val_loss: 0.4293 - val_accuracy: 0.7968
Epoch 38/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3784 - accuracy: 0.8258 - val_loss: 0.4340 - val_accuracy: 0.7921
Epoch 39/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3772 - accuracy: 0.8270 - val_loss: 0.4366 - val_accuracy: 0.7897
Epoch 40/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3811 - accuracy: 0.8217 - val_loss: 0.4409 - val_accuracy: 0.7903
Epoch 41/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3765 - accuracy: 0.8245 - val_loss: 0.4287 - val_accuracy: 0.7980
Epoch 42/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3780 - accuracy: 0.8321 - val_loss: 0.4336 - val_accuracy: 0.7944
Epoch 43/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3744 - accuracy: 0.8273 - val_loss: 0.4314 - val_accuracy: 0.7927
Epoch 44/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3788 - accuracy: 0.8298 - val_loss: 0.4331 - val_accuracy: 0.7998
Epoch 45/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3786 - accuracy: 0.8260 - val_loss: 0.4384 - val_accuracy: 0.7903
Epoch 46/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3721 - accuracy: 0.8306 - val_loss: 0.4363 - val_accuracy: 0.7909
Epoch 47/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3710 - accuracy: 0.8298 - val_loss: 0.4380 - val_accuracy: 0.7915
Epoch 48/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3728 - accuracy: 0.8275 - val_loss: 0.4378 - val_accuracy: 0.7891
Epoch 49/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3742 - accuracy: 0.8265 - val_loss: 0.4396 - val_accuracy: 0.7927
Epoch 50/50
124/124 [==============================] - 0s 2ms/step - loss: 0.3700 - accuracy: 0.8311 - val_loss: 0.4394 - val_accuracy: 0.7903

In [40]:
model.evaluate(x_test,y_test)

44/44 [==============================] - 0s 1ms/step - loss: 0.4633 - accuracy: 0.7889

[0.4632788300514221, 0.7889125943183899]

In [41]:
y_pred = model.predict(x_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

44/44 [==============================] - 0s 907us/step

ValueError: Classification metrics can't handle a mix of continuous and binary targets

In [43]:
# the error is occuring because we have got the y_pred as float and 2D value, we need to convert in=t into binary classification and 1D
print(y_pred)
print("\n")
print(y_test)

[[0.0957552 ]
 [0.31384885]
 [0.00510097]
 ...
 [0.82191503]
 [0.8499501 ]
 [0.32523555]]


2660    0
744     0
5579    1
64      1
3287    1
       ..
2024    0
4396    1
4081    1
1297    0
4899    1
Name: Churn, Length: 1407, dtype: int64

In [44]:
y_pred = y_pred.ravel() # convert ND to 1D

In [45]:
for i in range(len(y_pred)):
    if(y_pred[i]>0.5):
        y_pred[i]=1
    else:
        y_pred[i]=0

In [46]:
y_pred = y_pred.astype(int)

In [47]:
y_pred

array([0, 0, 0, ..., 1, 1, 0])

In [48]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("accuracy: ",accuracy_score(y_pred,y_test),"\n"), print("classification_report: ",classification_report(y_pred,y_test))
print("confusion_matrix: \n",confusion_matrix(y_pred,y_test))

accuracy:  0.7889125799573561

classification_report:                precision    recall  f1-score   support

           0       0.88      0.83      0.86      1058
           1       0.56      0.66      0.61       349

    accuracy                           0.79      1407
   macro avg       0.72      0.75      0.73      1407
weighted avg       0.80      0.79      0.79      1407

confusion_matrix:
 [[880 178]
 [119 230]]

## ------------------------------------------------END------------------------------------------------